language: python

os:
  - linux
  - osx

services:
  - docker

before_install:
  - docker build -t gary29198/example .
  - docker login -u gary29198 -p $DOCKER_PASSWORD
  - docker push gary29198/example

deploy:
  provider: script
  script: docker pull gary29198/example && docker run gary29198/example
  on:
    branch: master
